/**
 * BQN Help Documentation
 * 
 * Auto-generated by scripts/scrape-bqn-docs.cjs
 * Source: https://mlochbaum.github.io/BQN/help/index.html
 * 
 * Run `node scripts/scrape-bqn-docs.cjs` to update from upstream docs.
 * 
 * LICENSE ATTRIBUTION:
 * The documentation content in this file is derived from the BQN project.
 * Copyright (c) 2020, Marshall Lochbaum
 * Repository: https://github.com/mlochbaum/BQN
 * License: ISC License
 * See THIRD_PARTY_LICENSES.md for full license text.
 */

/**
 * Metadata about the scraped documentation
 */
export const bqnDocsMeta = {
    "language": "BQN",
    "source": "https://mlochbaum.github.io/BQN/help/index.html",
    "version": "2.0.0"
};

/**
 * BQN primitive documentation for hover tooltips
 * 
 * Structure for each glyph:
 * - glyph: The primitive character
 * - type: 'function' | '1-modifier' | '2-modifier' | 'syntax'
 * - name: Display name (e.g., "Deshape, Reshape")
 * - description: Concise description from help docs
 * - example: Code example
 * - docUrl: Link to full documentation
 */
export const bqnGlyphDocs = {
    "+": {
        "glyph": "+",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/conjugate_add.html",
        "monad": {
            "name": "Conjugate",
            "description": "Complex conjugate of 𝕩. BQN doesn't support complex numbers yet, so it has no effect.",
            "example": "+ 1\n1\n\n    + ¯1\n¯1"
        },
        "dyad": {
            "name": "Add",
            "description": "𝕨 added to 𝕩. Either 𝕨 or 𝕩 can be a character, and if so, the other has to be an integer. Pervasive.",
            "example": "1 + 2\n3\n\n    1 + 2‿3‿4\n⟨ 3 4 5 ⟩\n\n    'a' + 4\n'e'"
        }
    },
    "-": {
        "glyph": "-",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/negate_subtract.html",
        "monad": {
            "name": "Negate",
            "description": "Additive Inverse of 𝕩. Pervasive.",
            "example": "- 1\n¯1\n\n    - ¯1\n1"
        },
        "dyad": {
            "name": "Subtract",
            "description": "Subtract 𝕩 from 𝕨. 𝕨 and 𝕩 can be characters or numbers. Pervasive.",
            "example": "1 - 2\n¯1\n\n    1 - 2‿3‿4\n⟨ ¯1 ¯2 ¯3 ⟩\n\n    'a' - 4\n']'\n\n    'b' - 'a'\n1"
        }
    },
    "×": {
        "glyph": "×",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/sign_multiply.html",
        "monad": {
            "name": "Sign",
            "description": "¯1 if 𝕩 < 0. 0 if 𝕩 = 0. 1 if 𝕩 > 0",
            "example": "× ¯5‿0‿5‿1\n⟨ ¯1 0 1 1 ⟩"
        },
        "dyad": {
            "name": "Multiply",
            "description": "𝕨 multiplied by 𝕩. Pervasive.",
            "example": "1 × 2\n2\n\n    2 × 2‿3‿4\n⟨ 4 6 8 ⟩"
        }
    },
    "÷": {
        "glyph": "÷",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/reciprocal_divide.html",
        "monad": {
            "name": "Reciprocal",
            "description": "Gives 1 ÷ 𝕩. Pervasive.",
            "example": "÷ 5\n0.2"
        },
        "dyad": {
            "name": "Divide",
            "description": "𝕨 divided by 𝕩. Pervasive.",
            "example": "5 ÷ 4\n1.25\n\n    14 ÷ 7\n2"
        }
    },
    "⋆": {
        "glyph": "⋆",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/exponential_power.html",
        "monad": {
            "name": "Exponential",
            "description": "e (Euler's constant) to the power of 𝕩. Pervasive.",
            "example": "⋆ 0‿1‿2‿3\n⟨ 1 2.718281828459045 7.38905609893065 20.085536923187668 ⟩"
        },
        "dyad": {
            "name": "Power",
            "description": "𝕨 to the power of 𝕩. Pervasive.",
            "example": "2 ⋆ 5\n32\n\n    8‿5‿9 ⋆ 2\n⟨ 64 25 81 ⟩\n\n    2‿3 ⋆ 3‿¯4\n⟨ 8 0.012345679012345678 ⟩"
        }
    },
    "√": {
        "glyph": "√",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/squareroot_root.html",
        "monad": {
            "name": "Square root",
            "description": "Pervasive.",
            "example": "√ 2\n1.4142135623730951"
        },
        "dyad": {
            "name": "Root",
            "description": "𝕨th root of 𝕩. Pervasive.",
            "example": "2 √ 2\n1.4142135623730951\n\n    1‿2‿3‿4 √ 4\n⟨ 4 2 1.5874010519681994 1.4142135623730951 ⟩"
        }
    },
    "⌊": {
        "glyph": "⌊",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/floor_minimum.html",
        "monad": {
            "name": "Floor",
            "description": "Round 𝕩 down to the nearest integer. Pervasive.",
            "example": "⌊ 1.2‿π‿3‿7.89\n⟨ 1 3 3 7 ⟩"
        },
        "dyad": {
            "name": "Minimum",
            "description": "Minimum of 𝕨 and 𝕩. Pervasive.",
            "example": "1 ⌊ 2\n1\n\n    2‿3 ⌊ 4‿2\n⟨ 2 2 ⟩"
        }
    },
    "⌈": {
        "glyph": "⌈",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/ceiling_maximum.html",
        "monad": {
            "name": "Ceiling",
            "description": "Round 𝕩 up to the nearest integer. Pervasive.",
            "example": "⌈ 1.2‿π‿3‿7.89\n⟨ 2 4 3 8 ⟩"
        },
        "dyad": {
            "name": "Maximum",
            "description": "Maximum of 𝕨 and 𝕩. Pervasive.",
            "example": "1 ⌈ 2\n2\n\n    2‿3 ⌈ 4‿2\n⟨ 4 3 ⟩"
        }
    },
    "∧": {
        "glyph": "∧",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/sortup_and.html",
        "monad": {
            "name": "Sort Up",
            "description": "Sort array 𝕩 in ascending order.",
            "example": "∧ 3‿1‿4‿1‿5\n⟨ 1 1 3 4 5 ⟩"
        },
        "dyad": {
            "name": "Logical And",
            "description": "Logical And of 𝕨 and 𝕩. Pervasive.",
            "example": "1 ∧ 1\n1\n\n    1‿0 ∧ 1‿1\n⟨ 1 0 ⟩"
        }
    },
    "∨": {
        "glyph": "∨",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/sortdown_or.html",
        "monad": {
            "name": "Sort Down",
            "description": "Sort array 𝕩 in descending order.",
            "example": "∨ 3‿1‿4‿1‿5\n⟨ 5 4 3 1 1 ⟩"
        },
        "dyad": {
            "name": "Logical Or",
            "description": "Logical Or of 𝕨 and 𝕩. Pervasive.",
            "example": "1 ∨ 0\n1\n\n    1‿0 ∨ 1‿1\n⟨ 1 1 ⟩\n\n    0 ∨ 0\n0"
        }
    },
    "¬": {
        "glyph": "¬",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/not_span.html",
        "monad": {
            "name": "Logical Not",
            "description": "Logical Not of 𝕩. Pervasive.",
            "example": "¬ 0\n1\n\n    ¬ 1‿0\n⟨ 0 1 ⟩"
        },
        "dyad": {
            "name": "Span",
            "description": "Count of numbers in the inclusive range from 𝕩 to 𝕨. Pervasive.",
            "example": "3 ¬ 1\n3\n\n    3‿4 ¬ 0‿2\n⟨ 4 3 ⟩"
        }
    },
    "|": {
        "glyph": "|",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/absolutevalue_modulus.html",
        "monad": {
            "name": "Absolute Value",
            "description": "Absolute Value of 𝕩. Pervasive.",
            "example": "| ¯2\n2\n\n    | 1‿3‿¯4‿3\n⟨ 1 3 4 3 ⟩"
        },
        "dyad": {
            "name": "Modulus",
            "description": "Remainder of 𝕩 divided by 𝕨. Pervasive.",
            "example": "1 | 3\n0\n\n    2 | 3‿4‿¯5\n⟨ 1 0 1 ⟩"
        }
    },
    "≤": {
        "glyph": "≤",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/lessthanorequalto.html",
        "monad": {
            "name": "Lesser Than or Equal To",
            "description": "",
            "example": null
        }
    },
    "<": {
        "glyph": "<",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/enclose_lessthan.html",
        "monad": {
            "name": "Enclose",
            "description": "Create a unit array containing 𝕩. ((≢<𝕩) ≡ ⟨⟩)",
            "example": "<1\n┌·   \n· 1  \n    ┘\n\n\n    ≢<1\n⟨⟩"
        },
        "dyad": {
            "name": "Lesser Than",
            "description": "𝕨 and 𝕩 can both be either numbers or characters. Pervasive.",
            "example": "1 < 3\n1\n\n    2‿3‿0 < 3‿1‿0\n⟨ 1 0 0 ⟩"
        }
    },
    ">": {
        "glyph": ">",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/merge_greaterthan.html",
        "monad": {
            "name": "Merge",
            "description": "Combine an array of arrays into one array. All elements of 𝕩 must have the same rank, and the result rank is that plus the rank of 𝕩. Returns and boxed atoms unchanged.",
            "example": "a ← ⟨⟨1, 2⟩, ⟨3, 4⟩⟩\n\n    >a\n┌─     \n╵ 1 2  \n  3 4  \n      ┘\n\n    ≢a\n⟨ 2 ⟩\n\n    ≢>a\n⟨ 2 2 ⟩"
        },
        "dyad": {
            "name": "Greater Than",
            "description": "𝕨 and 𝕩 can both be either numbers or characters. Pervasive.",
            "example": "1 > 3\n0\n\n    2‿3‿0 > 3‿1‿0\n⟨ 0 1 0 ⟩\n\n    'a' > 'b'\n0"
        }
    },
    "≥": {
        "glyph": "≥",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/greaterthanorequalto.html",
        "monad": {
            "name": "Greater Than or Equal To",
            "description": "",
            "example": null
        }
    },
    "=": {
        "glyph": "=",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/rank_equals.html",
        "monad": {
            "name": "Rank",
            "description": "Returns the number of dimensions in 𝕩.",
            "example": "= 0\n0\n\n    = 3⥊0\n1\n\n    = 3‿3⥊0\n2\n\n    3‿3‿3 ⥊ ⟨⟨0⟩⟩\n┌─                   \n╎ ⟨ 0 ⟩ ⟨ 0 ⟩ ⟨ 0 ⟩  \n  ⟨ 0 ⟩ ⟨ 0 ⟩ ⟨ 0 ⟩  \n  ⟨ 0 ⟩ ⟨ 0 ⟩ ⟨ 0 ⟩  \n                     \n  ⟨ 0 ⟩ ⟨ 0 ⟩ ⟨ 0 ⟩  \n  ⟨ 0 ⟩ ⟨ 0 ⟩ ⟨ 0 ⟩  \n  ⟨ 0 ⟩ ⟨ 0 ⟩ ⟨ 0 ⟩  \n                     \n  ⟨ 0 ⟩ ⟨ 0 ⟩ ⟨ 0 ⟩  \n  ⟨ 0 ⟩ ⟨ 0 ⟩ ⟨ 0 ⟩  \n  ⟨ 0 ⟩ ⟨ 0 ⟩ ⟨ 0 ⟩  \n                    ┘"
        },
        "dyad": {
            "name": "Equal To",
            "description": "Do argument atoms match? Pervasive.",
            "example": "1 = 3\n0\n\n    2‿3‿0 = 3‿1‿0\n⟨ 0 0 1 ⟩\n\n    'a' = 'a'\n1"
        }
    },
    "≠": {
        "glyph": "≠",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/length_notequals.html",
        "monad": {
            "name": "Length",
            "description": "Length of the first dimension of 𝕩.",
            "example": "≠ 3\n1\n\n    ≠ ⟨1, 2, 3⟩\n3\n\n    ≠ 3‿4‿5⥊0\n3\n\n    ≠ 1‿4‿5⥊0\n1\n\n    ≠ 4‿4‿5⥊0\n4"
        },
        "dyad": {
            "name": "Not Equal To",
            "description": "Do argument atoms not match? Pervasive.",
            "example": "1 ≠ 3\n1\n\n    2‿3‿0 ≠ 3‿1‿0\n⟨ 1 1 0 ⟩\n\n    'a' ≠ 'a'\n0"
        }
    },
    "≡": {
        "glyph": "≡",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/depth_match.html",
        "monad": {
            "name": "Depth",
            "description": "Highest level of nesting in 𝕩.",
            "example": "≡ 2‿3‿4\n1\n\n    ≡ ⟨2,<3,4,<<<5⟩\n4\n\n    ≡ 9\n0"
        },
        "dyad": {
            "name": "Match",
            "description": "Does 𝕨 exactly match 𝕩?",
            "example": "1 ≡ ⟨1⟩\n0\n\n    ⟨1⟩ ≡ ⟨1⟩\n1"
        }
    },
    "≢": {
        "glyph": "≢",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/shape_notmatch.html",
        "monad": {
            "name": "Shape",
            "description": "Length of each dimension of x.",
            "example": "≢ 1\n⟨⟩\n\n    ≢ 1‿2\n⟨ 2 ⟩\n\n    ≢ 1‿2 ≍ 3‿4\n⟨ 2 2 ⟩"
        },
        "dyad": {
            "name": "Not Match",
            "description": "Does 𝕨 not exactly match 𝕩?",
            "example": "1 ≢ ⟨1⟩\n1\n\n    ⟨1⟩ ≢ ⟨1⟩\n0"
        }
    },
    "⊣": {
        "glyph": "⊣",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/identity_left.html",
        "monad": {
            "name": "Identity",
            "description": "Return 𝕩.",
            "example": "⊣ 5\n5"
        },
        "dyad": {
            "name": "Left",
            "description": "Return 𝕨.",
            "example": "5 ⊣ 8\n5\n\n    'a' ⊣ 1‿2‿3\n'a'"
        }
    },
    "⊢": {
        "glyph": "⊢",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/identity_right.html",
        "monad": {
            "name": "Identity",
            "description": "Return 𝕩.",
            "example": "⊢ 5\n5"
        },
        "dyad": {
            "name": "Right",
            "description": "Return 𝕩.",
            "example": "5 ⊢ 8\n8\n\n    'a' ⊢ 1‿2‿3\n⟨ 1 2 3 ⟩"
        }
    },
    "⥊": {
        "glyph": "⥊",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/deshape_reshape.html",
        "monad": {
            "name": "Deshape",
            "description": "Put all elements of 𝕩 in a rank 1 array, promoting to an array if necessary.",
            "example": "⥊ 1\n⟨ 1 ⟩\n\n    ⥊ 1‿2 ≍ 3‿4\n⟨ 1 2 3 4 ⟩"
        },
        "dyad": {
            "name": "Reshape",
            "description": "Put all elements of 𝕩 in an array of shape 𝕨, removing elements or repeating them cyclically if necessary. A single element in 𝕨 can be a function, which will be replaced with an appropriate length:",
            "example": "3‿3 ⥊ 3\n┌─       \n╵ 3 3 3  \n  3 3 3  \n  3 3 3  \n        ┘\n\n    2‿⌽‿2 ⥊ 1‿2‿3\n┌─     \n╎ 1 2  \n       \n  3 1  \n      ┘\n\n    2‿↑‿2 ⥊ 1‿2‿3\n┌─     \n╎ 1 2  \n       \n  3 0  \n      ┘"
        }
    },
    "∾": {
        "glyph": "∾",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/join_jointo.html",
        "monad": {
            "name": "Join",
            "description": "Join all elements of 𝕩 together. Element ranks must be compatible.",
            "example": "∾ ⟨1‿2, 3, 4‿5⟩\n⟨ 1 2 3 4 5 ⟩\n\n    m ← (3‿1≍⌜4‿2‿5) ⥊¨ 2‿3⥊↕6\n\n    ∾ m\n┌─                       \n╵ 0 0 0 0 1 1 2 2 2 2 2  \n  0 0 0 0 1 1 2 2 2 2 2  \n  0 0 0 0 1 1 2 2 2 2 2  \n  3 3 3 3 4 4 5 5 5 5 5  \n                        ┘"
        },
        "dyad": {
            "name": "Join To",
            "description": "Join 𝕨 to 𝕩 along the first axis.",
            "example": "\"abcd\" ∾ \"EFG\"\n\"abcdEFG\"\n\n    a ← 3‿3 ⥊ ↕9\n\n    c ← 4‿3 ⥊ ↕12\n\n    a∾c\n┌─         \n╵ 0  1  2  \n  3  4  5  \n  6  7  8  \n  0  1  2  \n  3  4  5  \n  6  7  8  \n  9 10 11  \n          ┘"
        }
    },
    "≍": {
        "glyph": "≍",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/solo_couple.html",
        "monad": {
            "name": "Solo",
            "description": "Add a dimension to 𝕩.",
            "example": "≍ 1\n⟨ 1 ⟩\n\n\n    ≍≍ 1\n┌─   \n╵ 1  \n    ┘\n\n\n    ≍≍≍ 1\n┌─   \n╎ 1  \n    ┘\n\n\n    ≍≍ 1‿2‿3‿4\n┌─         \n╎ 1 2 3 4  \n          ┘\n\n\n    ≍≍≍ 1‿2‿3‿4\n┌─         \n┆ 1 2 3 4  \n          ┘"
        },
        "dyad": {
            "name": "Couple",
            "description": "Join 𝕨 and 𝕩 along a newly created axis.",
            "example": "1 ≍ 3\n⟨ 1 3 ⟩\n\n    1‿2 ≍ 2‿3\n┌─     \n╵ 1 2  \n  2 3  \n      ┘"
        }
    },
    "⋈": {
        "glyph": "⋈",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/enlist_pair.html",
        "monad": {
            "name": "Enlist",
            "description": "Put 𝕩 in a single element list. (⟨𝕩⟩)",
            "example": "⋈ 1\n⟨ 1 ⟩\n\n    ⋈ 4‿4 ⥊ 3‿67‿8‿0\n┌─              \n· ┌─            \n  ╵ 3 67 8 0    \n    3 67 8 0    \n    3 67 8 0    \n    3 67 8 0    \n             ┘  \n               ┘"
        },
        "dyad": {
            "name": "Pair",
            "description": "Put 𝕨 and 𝕩 in a two element list. (⟨𝕨, 𝕩⟩)",
            "example": "1 ⋈ 2\n⟨ 1 2 ⟩\n\n    1 ⋈ \"dsdasdas\"\n⟨ 1 \"dsdasdas\" ⟩\n\n    (3‿3 ⥊ 3) ⋈ 67‿'a'‿\"example\"\n┌─                                \n· ┌─        ⟨ 67 'a' \"example\" ⟩  \n  ╵ 3 3 3                         \n    3 3 3                         \n    3 3 3                         \n          ┘                       \n                                 ┘"
        }
    },
    "↑": {
        "glyph": "↑",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/prefixes_take.html",
        "monad": {
            "name": "Prefixes",
            "description": "Prefixes of array 𝕩 along its first axis.",
            "example": "↑ 1‿2‿3‿4\n⟨ ⟨⟩ ⟨ 1 ⟩ ⟨ 1 2 ⟩ ⟨ 1 2 3 ⟩ ⟨ 1 2 3 4 ⟩ ⟩\n\n    a ← 3‿3 ⥊ ↕9\n\n    ↑ a\n┌─                                    \n· ↕0‿3 ┌─        ┌─        ┌─         \n       ╵ 0 1 2   ╵ 0 1 2   ╵ 0 1 2    \n               ┘   3 4 5     3 4 5    \n                         ┘   6 7 8    \n                                   ┘  \n                                     ┘"
        },
        "dyad": {
            "name": "Take",
            "description": "For each integer in 𝕨, take that many elements from each dimension of 𝕩. Negative numbers take from the end. If any of the elements in 𝕨 are greater than the length of their respective dimension, the dimension is extended with a fill value.",
            "example": "3 ↑ 1‿3‿5‿67\n⟨ 1 3 5 ⟩\n\n    b ← 4‿4 ⥊ ↕16\n\n    3‿3 ↑ b\n┌─        \n╵ 0 1  2  \n  4 5  6  \n  8 9 10  \n         ┘\n\n    5‿5 ↑ b\n┌─               \n╵  0  1  2  3 0  \n   4  5  6  7 0  \n   8  9 10 11 0  \n  12 13 14 15 0  \n   0  0  0  0 0  \n                ┘\n\n    3‿¯3 ↑ b\n┌─         \n╵ 1  2  3  \n  5  6  7  \n  9 10 11  \n          ┘"
        }
    },
    "↓": {
        "glyph": "↓",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/suffixes_drop.html",
        "monad": {
            "name": "Suffixes",
            "description": "Suffixes of array 𝕩 along its first axis.",
            "example": "↓ 1‿2‿3‿4\n⟨ ⟨ 1 2 3 4 ⟩ ⟨ 2 3 4 ⟩ ⟨ 3 4 ⟩ ⟨ 4 ⟩ ⟨⟩ ⟩\n\n    a ← 3‿3 ⥊ ↕9\n\n    ↓ a\n┌─                                    \n· ┌─        ┌─        ┌─        ↕0‿3  \n  ╵ 0 1 2   ╵ 3 4 5   ╵ 6 7 8         \n    3 4 5     6 7 8           ┘       \n    6 7 8           ┘                 \n          ┘                           \n                                     ┘"
        },
        "dyad": {
            "name": "Drop",
            "description": "For each integer in 𝕨, drop that many elements from the beginning of each dimension of 𝕩. Negative numbers drop from the end.",
            "example": "3 ↓ 1‿3‿5‿67\n⟨ 67 ⟩\n\n    b ← 4‿4 ⥊ ↕16\n\n    3‿3 ↓ b\n┌─    \n╵ 15  \n     ┘\n\n    5‿5 ↓ b\n┌┐\n└┘\n\n\n    3‿¯3 ↓ b\n┌─    \n╵ 12  \n     ┘"
        }
    },
    "↕": {
        "glyph": "↕",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/range_windows.html",
        "monad": {
            "name": "Range",
            "description": "Return all indices that would index into an array of shape 𝕩. When given a single number, range from 0 to 𝕩-1.",
            "example": "↕ 4\n⟨ 0 1 2 3 ⟩\n\n    ↕ 4‿5\n┌─                                         \n╵ ⟨ 0 0 ⟩ ⟨ 0 1 ⟩ ⟨ 0 2 ⟩ ⟨ 0 3 ⟩ ⟨ 0 4 ⟩  \n  ⟨ 1 0 ⟩ ⟨ 1 1 ⟩ ⟨ 1 2 ⟩ ⟨ 1 3 ⟩ ⟨ 1 4 ⟩  \n  ⟨ 2 0 ⟩ ⟨ 2 1 ⟩ ⟨ 2 2 ⟩ ⟨ 2 3 ⟩ ⟨ 2 4 ⟩  \n  ⟨ 3 0 ⟩ ⟨ 3 1 ⟩ ⟨ 3 2 ⟩ ⟨ 3 3 ⟩ ⟨ 3 4 ⟩  \n                                          ┘"
        },
        "dyad": {
            "name": "Windows",
            "description": "Overlapping slices from 𝕩 of shape 𝕨.",
            "example": "5 ↕ \"abcdefg\"\n┌─       \n╵\"abcde  \n  bcdef  \n  cdefg\" \n        ┘\n\n    a ← 3‿3⥊↕9\n\n    2‿2 ↕ a\n┌─     \n┆ 0 1  \n  3 4  \n       \n  1 2  \n  4 5  \n       \n       \n  3 4  \n  6 7  \n       \n  4 5  \n  7 8  \n      ┘"
        }
    },
    "»": {
        "glyph": "»",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/nudge_shiftbefore.html",
        "monad": {
            "name": "Nudge",
            "description": "Remove the last element of 𝕩, add a cell of fill values to the start of the first axis of 𝕩.",
            "example": "» 1‿2‿3\n⟨ 0 1 2 ⟩\n\n    » 3‿3 ⥊ 9\n┌─       \n╵ 0 0 0  \n  9 9 9  \n  9 9 9  \n        ┘"
        },
        "dyad": {
            "name": "Shift Before",
            "description": "Remove the last ≠𝕨 (length) major cells from 𝕩, join 𝕨 to the start of 𝕩. Ranks must match.",
            "example": "78 » 1‿2‿3\n⟨ 78 1 2 ⟩\n\n    1‿2 » 1‿2‿3\n⟨ 1 2 1 ⟩\n\n    a ← 3‿3 ⥊ 9\n\n    1‿2‿3 » a\n┌─       \n╵ 1 2 3  \n  9 9 9  \n  9 9 9  \n        ┘"
        }
    },
    "«": {
        "glyph": "«",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/nudgeback_shiftafter.html",
        "monad": {
            "name": "Nudge Back",
            "description": "Remove the first element of 𝕩, add a cell of fill values to the end of the first axis of 𝕩.",
            "example": "« 1‿2‿3\n⟨ 2 3 0 ⟩\n\n    « 3‿3 ⥊ 9\n┌─       \n╵ 9 9 9  \n  9 9 9  \n  0 0 0  \n        ┘"
        },
        "dyad": {
            "name": "Shift After",
            "description": "Remove the first ≠𝕨 (length) major cells from 𝕩, join 𝕨 to the end of 𝕩. Ranks must match.",
            "example": "78 « 1‿2‿3\n⟨ 2 3 78 ⟩\n\n    8‿5 « 1‿2‿3\n⟨ 3 8 5 ⟩\n\n    a ← 3‿3 ⥊ 9\n\n    1‿2‿3 « a\n┌─       \n╵ 9 9 9  \n  9 9 9  \n  1 2 3  \n        ┘"
        }
    },
    "⌽": {
        "glyph": "⌽",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/reverse_rotate.html",
        "monad": {
            "name": "Reverse",
            "description": "Reverse 𝕩 along the first axis.",
            "example": "⌽ 1‿2‿3\n⟨ 3 2 1 ⟩\n\n    a ← 3‿3 ⥊ ↕9\n\n    ⌽ a\n┌─       \n╵ 6 7 8  \n  3 4 5  \n  0 1 2  \n        ┘"
        },
        "dyad": {
            "name": "Rotate",
            "description": "Move the first 𝕨 elements of 𝕩 to its end. Negative 𝕨 reverses the direction of rotation.",
            "example": "2 ⌽ 1‿2‿3\n⟨ 3 1 2 ⟩\n\n    b ← 3‿3 ⥊ ↕9\n\n    2 ⌽ b\n┌─       \n╵ 6 7 8  \n  0 1 2  \n  3 4 5  \n        ┘"
        }
    },
    "⍉": {
        "glyph": "⍉",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/transpose_reorderaxes.html",
        "monad": {
            "name": "Transpose",
            "description": "Move the first axis of 𝕩 to the end.",
            "example": "a ← 3‿3 ⥊ ↕9\n\n    ⍉ a\n┌─       \n╵ 0 3 6  \n  1 4 7  \n  2 5 8  \n        ┘\n\n    b ← 1‿2‿3 ⥊ ↕6\n\n    ≢⍉ b\n⟨ 2 3 1 ⟩"
        },
        "dyad": {
            "name": "Reorder Axes",
            "description": "Rearrange the axes of 𝕩 as per the axis indices in 𝕨.",
            "example": "≢ c ← 2‿3‿4‿5‿6 ⥊1\n⟨ 2 3 4 5 6 ⟩\n\n    ≢ 1‿3‿2‿0‿4 ⍉ c\n⟨ 5 2 4 3 6 ⟩"
        }
    },
    "/": {
        "glyph": "/",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/indices_replicate.html",
        "monad": {
            "name": "Indices",
            "description": "Repeat the index of each element in 𝕩 by the element's value. 𝕩 must be rank 1.",
            "example": "/ 1‿2‿3\n⟨ 0 1 1 2 2 2 ⟩\n\n    / 1‿0‿1\n⟨ 0 2 ⟩"
        },
        "dyad": {
            "name": "Replicate",
            "description": "Repeat each major cell in 𝕩 by the corresponding element in 𝕨. Unit 𝕨 applies to all elements.",
            "example": "3 / \"copy\"\n\"cccooopppyyy\"\n\n    1‿0‿1 / 1‿2‿3\n⟨ 1 3 ⟩"
        }
    },
    "⍋": {
        "glyph": "⍋",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/gradeup_binsup.html",
        "monad": {
            "name": "Grade Up",
            "description": "Indices of 𝕩 that would sort its major cells in ascending order.",
            "example": "a ← 3‿2‿1\n\n    ⍋ a\n⟨ 2 1 0 ⟩\n\n    (⍋a) ⊏ a\n⟨ 1 2 3 ⟩"
        },
        "dyad": {
            "name": "Bins Up",
            "description": "Binary search for each cell of 𝕩 in 𝕨, returning the number of major cells in 𝕨 less than or equal to that cell. 𝕨 must be sorted in ascending order.",
            "example": "3‿4‿5‿7 ⍋ 2\n┌·   \n· 0  \n    ┘\n\n    3‿4‿5‿7 ⍋ 2‿6\n⟨ 0 3 ⟩"
        }
    },
    "⍒": {
        "glyph": "⍒",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/gradedown_binsdown.html",
        "monad": {
            "name": "Grade Down",
            "description": "Indices of 𝕩 that would sort its major cells in descending order.",
            "example": "a ← 1‿2‿3\n\n    ⍒ a\n⟨ 2 1 0 ⟩\n\n    (⍒a) ⊏ a\n⟨ 3 2 1 ⟩"
        },
        "dyad": {
            "name": "Bins Down",
            "description": "Binary search for each cell of 𝕩 in 𝕨, returning the number of major cells in 𝕨 greater than or equal to that cell. 𝕨 must be sorted in descending order. Right Pervasive.",
            "example": "7‿5‿4‿3 ⍒ 2\n┌·   \n· 4  \n    ┘\n\n    7‿5‿4‿3 ⍒ 2‿6\n⟨ 4 1 ⟩"
        }
    },
    "⊏": {
        "glyph": "⊏",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/firstcell_select.html",
        "monad": {
            "name": "First Cell",
            "description": "First major cell of 𝕩.",
            "example": "⊏ ⟨1, 2, 3⟩\n┌·   \n· 1  \n    ┘\n\n    a ← 3‿3 ⥊ ↕9\n\n    ⊏ a\n⟨ 0 1 2 ⟩"
        },
        "dyad": {
            "name": "Select",
            "description": "Select the major cells of 𝕩 at the indices in 𝕨.",
            "example": "2‿0 ⊏ ⟨1, 2, 3⟩\n⟨ 3 1 ⟩\n\n    b ← 3‿3 ⥊ ↕9\n\n    2‿0 ⊏ b\n┌─       \n╵ 6 7 8  \n  0 1 2  \n        ┘"
        }
    },
    "⊑": {
        "glyph": "⊑",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/first_pick.html",
        "monad": {
            "name": "First",
            "description": "First element of 𝕩.",
            "example": "⊑ ⟨1, 2, 3⟩\n1\n\n    a ← 3‿3 ⥊ ↕9\n\n    ⊑ a\n0"
        },
        "dyad": {
            "name": "Pick",
            "description": "Pick the element of 𝕩 at index 𝕨.",
            "example": "2 ⊑ ⟨1, 2, 3⟩\n3\n\n    b ← 3‿3 ⥊ ↕9\n\n    2‿0 ⊑ b\n6"
        }
    },
    "⊐": {
        "glyph": "⊐",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/classify_indexof.html",
        "monad": {
            "name": "Classify",
            "description": "Translate major cells of 𝕩 to unique ID numbers based on first occurrence.",
            "example": "⊐ 5‿6‿2‿2‿5‿1\n⟨ 0 1 2 2 0 3 ⟩\n\n    a ← 3‿3 ⥊ 0‿1‿2‿9‿0‿9‿0‿1‿2\n\n    ⊐ a\n⟨ 0 1 0 ⟩"
        },
        "dyad": {
            "name": "Index Of",
            "description": "First index of each major cell of 𝕩 in 𝕨. Rank of 𝕩 must be at least cell rank of 𝕨. If a cell is not found in 𝕨, the length of 𝕨 (≠𝕨) is used for that position.",
            "example": "5‿6‿2‿2‿5‿1 ⊐ 5‿7‿1‿6\n⟨ 0 6 5 1 ⟩\n\n    b ← 3‿3 ⥊ 0‿1‿2‿9‿0‿9‿0‿1‿2\n\n    b ⊐ ≍9‿0‿9\n⟨ 1 ⟩"
        }
    },
    "⊒": {
        "glyph": "⊒",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/occurrencecount_progressiveindexof.html",
        "monad": {
            "name": "Occurrence Count",
            "description": "Number of times each major cell of 𝕩 has occurred before the current position.",
            "example": "⊒   2‿7‿1‿8‿1‿7‿1‿8‿2‿8‿4\n⟨ 0 0 0 0 1 1 2 1 1 2 0 ⟩\n\n    ≍⟜⊒ 2‿7‿1‿8‿1‿7‿1‿8‿2‿8‿4\n┌─                       \n╵ 2 7 1 8 1 7 1 8 2 8 4  \n  0 0 0 0 1 1 2 1 1 2 0  \n                        ┘"
        },
        "dyad": {
            "name": "Progressive Index Of",
            "description": "Index of the first unused match of each major cell of 𝕩 in 𝕨. If there are no more matches left, the length of 𝕨 is placed in that position.",
            "example": "\"aaa\" ⊒ \"aaaaa\"\n⟨ 0 1 2 3 3 ⟩\n\n    \"aaabb\" ⊒ \"ababababab\"\n⟨ 0 3 1 4 2 5 5 5 5 5 ⟩"
        }
    },
    "∊": {
        "glyph": "∊",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/markfirst_memberof.html",
        "monad": {
            "name": "Mark Firsts",
            "description": "Mark the first occurrence of each major cell in 𝕩 with a 1, and all other occurrences with a 0.",
            "example": "∊ 4‿5‿6‿6‿4‿7‿5\n⟨ 1 1 1 0 0 1 0 ⟩\n\n    a ← 3‿3 ⥊ ↕9\n\n    ∊ a\n⟨ 1 1 1 ⟩"
        },
        "dyad": {
            "name": "Member Of",
            "description": "Is each cell in 𝕨 a major cell of 𝕩?",
            "example": "⟨1⟩ ∊ ↕9\n⟨ 1 ⟩\n\n    b ← 3‿3 ⥊ ↕9\n\n    ⟨0‿1‿2⟩ ∊ b\n┌·   \n· 0  \n    ┘\n\n    ⟨1‿3 ⥊ 0‿1‿2⟩ ∊ b\n┌·   \n· 0  \n    ┘"
        }
    },
    "⍷": {
        "glyph": "⍷",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/deduplicate_find.html",
        "monad": {
            "name": "Deduplicate",
            "description": "Unique major cells of 𝕩.",
            "example": "⍷ 4‿5‿6‿6‿4‿7‿5\n⟨ 4 5 6 7 ⟩\n\n    a ← 3‿3 ⥊ ↕6\n\n    ⍷ a\n┌─       \n╵ 0 1 2  \n  3 4 5  \n        ┘"
        },
        "dyad": {
            "name": "Find",
            "description": "Mark the top left location of the occurrences of 𝕨 in 𝕩 with a 1, and other locations with 0. Result is the same shape as (≢𝕨)↕𝕩.",
            "example": "\"string\" ⍷ \"substring\"\n⟨ 0 0 0 1 ⟩\n\n    \"loooooong\" ⍷ \"short\"\n⟨⟩\n\n    b ← 7 (4|⋆˜)⌜○↕ 9\n\n    c ← (0‿3‿0≍0‿1‿0)\n\n    c ⍷ b\n┌─               \n╵ 0 0 0 0 0 0 0  \n  0 0 0 0 0 0 0  \n  0 0 0 0 0 0 0  \n  0 0 1 0 0 0 1  \n  0 0 0 0 0 0 0  \n  0 0 1 0 0 0 1  \n                ┘"
        }
    },
    "⊔": {
        "glyph": "⊔",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/groupindices_group.html",
        "monad": {
            "name": "Group Indices",
            "description": "Group the indices of the major cells of 𝕩 by their respective values. 𝕩 must consist of integers. Groups start from 0.",
            "example": "⊔ 4‿5‿6‿6‿4‿7‿5\n⟨ ⟨⟩ ⟨⟩ ⟨⟩ ⟨⟩ ⟨ 0 4 ⟩ ⟨ 1 6 ⟩ ⟨ 2 3 ⟩ ⟨ 5 ⟩ ⟩\n\n    (↕8) ≍ ⊔ 4‿5‿6‿6‿4‿7‿5\n┌─                                           \n╵ 0  1  2  3  4       5       6       7      \n  ⟨⟩ ⟨⟩ ⟨⟩ ⟨⟩ ⟨ 0 4 ⟩ ⟨ 1 6 ⟩ ⟨ 2 3 ⟩ ⟨ 5 ⟩  \n                                            ┘"
        },
        "dyad": {
            "name": "Group",
            "description": "Group the major cells of 𝕩 by their respective indices in 𝕨. If an element corresponds to ¯1, it is excluded from grouping. An extra element can be added to the end of 𝕨 to specify length of the result.",
            "example": "1‿0‿1‿2‿2‿3‿3  ⊔ 4‿5‿6‿6‿4‿7‿5\n⟨ ⟨ 5 ⟩ ⟨ 4 6 ⟩ ⟨ 6 4 ⟩ ⟨ 7 5 ⟩ ⟩\n\n    1‿0‿1‿¯1‿¯1‿3‿3  ⊔ 4‿5‿6‿6‿4‿7‿5\n⟨ ⟨ 5 ⟩ ⟨ 4 6 ⟩ ⟨⟩ ⟨ 7 5 ⟩ ⟩\n\n    1‿0‿1‿¯1‿¯1‿3‿3‿10  ⊔ 4‿5‿6‿6‿4‿7‿5\n⟨ ⟨ 5 ⟩ ⟨ 4 6 ⟩ ⟨⟩ ⟨ 7 5 ⟩ ⟨⟩ ⟨⟩ ⟨⟩ ⟨⟩ ⟨⟩ ⟨⟩ ⟩"
        }
    },
    "!": {
        "glyph": "!",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/assert_assertwithmessage.html",
        "monad": {
            "name": "Assert",
            "description": "Throw an error if 𝕩 is not 1.",
            "example": "! 1\n1\n\n    ! 2\nError: Assertion error\n\n    ! \"hello\"\nError: hello"
        },
        "dyad": {
            "name": "Assert With Message",
            "description": "Throw an error with message 𝕨 if 𝕩 is not 1.",
            "example": "\"hi\" ! 1\n1\n\n    \"two\" ! 2\nError: two\n\n    \"hello error\" ! \"hello\"\nError: hello error"
        }
    },
    "˙": {
        "glyph": "˙",
        "type": "1-modifier",
        "docUrl": "https://mlochbaum.github.io/BQN/help/constant.html",
        "monad": {
            "name": "Constant",
            "description": "Returns a function that will always return 𝕗.",
            "example": "\"hello\" 1˙ 2\n1\n\n    \"hello\" {𝕨+𝕩}˙ 2\n(function block)"
        }
    },
    "˜": {
        "glyph": "˜",
        "type": "1-modifier",
        "docUrl": "https://mlochbaum.github.io/BQN/help/self_swap.html",
        "monad": {
            "name": "Self",
            "description": "Supplies 𝕩 as a left argument to 𝔽 (𝕩 𝔽 𝕩).",
            "example": "1 + 1\n2\n\n    +˜ 1\n2"
        },
        "dyad": {
            "name": "Swap",
            "description": "Swaps the arguments of 𝔽 (𝕩 𝔽 𝕨).",
            "example": "1 - 2\n¯1\n\n    1 -˜ 2\n1"
        }
    },
    "∘": {
        "glyph": "∘",
        "type": "2-modifier",
        "docUrl": "https://mlochbaum.github.io/BQN/help/atop.html",
        "monad": {
            "name": "Atop",
            "description": "Apply 𝔾 to 𝕩, then apply 𝔽 (𝔽 𝔾 𝕩). 𝔽 and 𝔾 must be monadic.",
            "example": "-∘- 5\n5\n\n    - - 5\n5"
        },
        "dyad": {
            "name": "Dyadic Atop",
            "description": "Apply 𝔾 to 𝕨 and 𝕩, then apply 𝔽 (𝔽 (𝕨 𝔾 𝕩)). 𝔽 must be monadic, and 𝔾 must be dyadic.",
            "example": "1 -∘+ 2\n¯3\n\n    1 - + 2\n¯1\n\n    - 1 + 2\n¯3"
        }
    },
    "○": {
        "glyph": "○",
        "type": "2-modifier",
        "docUrl": "https://mlochbaum.github.io/BQN/help/over.html",
        "monad": {
            "name": "Atop",
            "description": "Apply 𝔾 to 𝕩, then apply 𝔽 (𝔽 𝔾 𝕩). 𝔽 and 𝔾 must be monadic.",
            "example": "-○- 5\n5\n\n    - - 5\n5"
        },
        "dyad": {
            "name": "Over",
            "description": "Apply 𝔾 to 𝕨 and 𝕩, then apply 𝔽 to them ((𝔾 𝕨) 𝔽 (𝔾 𝕩)). 𝔽 must be dyadic, 𝔾 must be monadic.",
            "example": "1 +○- 2\n¯3\n\n    1 + - 2\n¯1\n\n    (- 1) + (- 2)\n¯3"
        }
    },
    "⊸": {
        "glyph": "⊸",
        "type": "2-modifier",
        "docUrl": "https://mlochbaum.github.io/BQN/help/before_bind.html",
        "monad": {
            "name": "Bind Left",
            "description": "Apply 𝔽 to 𝕩, and supply it as a left argument to 𝔾 ((𝔽 𝕩) 𝔾 𝕩). 𝔽 must be monadic, 𝔾 must be dyadic.",
            "example": "-⊸+ 9\n0\n\n    - + 9\n¯9\n\n    (- 9) + 9\n0"
        },
        "dyad": {
            "name": "Before",
            "description": "Apply 𝔽 to 𝕨, and supply it as a left argument to 𝔾 ((𝔽 𝕨) 𝔾 𝕩). 𝔽 must be monadic, 𝔾 must be dyadic.",
            "example": "2 -⊸+ 1\n¯1\n\n    2 - + 1\n1\n\n    (- 2) + 1\n¯1"
        }
    },
    "⟜": {
        "glyph": "⟜",
        "type": "2-modifier",
        "docUrl": "https://mlochbaum.github.io/BQN/help/after_bind.html",
        "monad": {
            "name": "Bind",
            "description": "Apply 𝔾 to 𝕩, and supply it as a right argument to 𝔽 (𝕩 𝔽 (𝔾 𝕩)). 𝔽 must be dyadic, 𝔾 must be monadic.",
            "example": "×⟜- 9\n¯81\n\n    × - 9\n¯1\n\n    9 × (- 9)\n¯81"
        },
        "dyad": {
            "name": "After",
            "description": "Apply 𝔾 to 𝕩, and supply it as a right argument to 𝔽 (𝕨 𝔽 (𝔾 𝕩)). 𝔽 must be dyadic, 𝔾 must be monadic.",
            "example": "2 ×⟜- 1\n¯2\n\n    2 × (- 1)\n¯2"
        }
    },
    "⌾": {
        "glyph": "⌾",
        "type": "2-modifier",
        "docUrl": "https://mlochbaum.github.io/BQN/help/under.html",
        "monad": {
            "name": "Under",
            "description": "Apply transformation 𝔾 to all arguments. Apply 𝔽 to the transformed arguments. Undo transformation 𝔾. A function invertible by ⁼ (Undo)",
            "example": "9⌾(1⊸⊑) 1‿2‿3\n⟨ 1 9 3 ⟩\n\n    √⁼ (√1) + (√9)\n16\n\n    1 +⌾√ 9\n16"
        }
    },
    "⊘": {
        "glyph": "⊘",
        "type": "2-modifier",
        "docUrl": "https://mlochbaum.github.io/BQN/help/valences.html",
        "monad": {
            "name": "Valences",
            "description": "Apply 𝔽 to 𝕩.",
            "example": "+⊘- 5\n5\n\n    -⊘+ 5\n¯5"
        },
        "dyad": {
            "name": "Dyadic Valences",
            "description": "Apply 𝔾 to 𝕨 and 𝕩.",
            "example": "4 +⊘- 5\n¯1\n\n    4 -⊘+ 5\n9"
        }
    },
    "◶": {
        "glyph": "◶",
        "type": "2-modifier",
        "docUrl": "https://mlochbaum.github.io/BQN/help/choose.html",
        "monad": {
            "name": "Choose",
            "description": "Apply 𝔽 to the arguments and use the result to pick (⊑) a function from list 𝕘. Apply the picked function to the arguments.",
            "example": "F ← ⊢◶+‿-‿÷‿×\n\n    F 0\n0\n\n    F 1\n¯1\n\n    F 2\n0.5\n\n    F 3\n1"
        }
    },
    "⎊": {
        "glyph": "⎊",
        "type": "2-modifier",
        "docUrl": "https://mlochbaum.github.io/BQN/help/catch.html",
        "monad": {
            "name": "Catch",
            "description": "Apply 𝔽 to the arguments. If an error happens when 𝔽 is applied, cancel its execution, apply 𝔾 to the arguments and return its result. Otherwise, return the result of 𝔽.",
            "example": "∾⎊{\"error occurred with argument: \"∾•Fmt 𝕩} 1\n\"error occurred with argument: 1\"\n\n    ∾⎊{\"error occurred with argument: \"∾•Fmt 𝕩} ⟨⟨1,2⟩, ⟨3,4⟩⟩\n⟨ 1 2 3 4 ⟩"
        }
    },
    "⎉": {
        "glyph": "⎉",
        "type": "2-modifier",
        "docUrl": "https://mlochbaum.github.io/BQN/help/rank.html",
        "monad": {
            "name": "Rank",
            "description": "Apply 𝔽 to cells at ranks given in 𝕘. Non-negative numbers indicate the rank of the cell and negative ones indicate the difference from full rank. The ranks applied are given by the following:",
            "example": "a ← 3‿2‿4⥊\"ABCDEFGHIJKLMNOPQRSTUVWXYZ\"\n\n    ⌽⎉2 a\n┌─      \n╎\"EFGH  \n  ABCD  \n        \n ·MNOP  \n  IJKL  \n        \n ·UVWX  \n  QRST\" \n       ┘"
        }
    },
    "˘": {
        "glyph": "˘",
        "type": "1-modifier",
        "docUrl": "https://mlochbaum.github.io/BQN/help/cells.html",
        "monad": {
            "name": "Cells",
            "description": "Apply 𝔽 to/between the major cells of the arguments. (𝔽⎉¯1)",
            "example": "a ← 3‿3 ⥊ ↕9\n\n\n    <˘ a\n⟨ ⟨ 0 1 2 ⟩ ⟨ 3 4 5 ⟩ ⟨ 6 7 8 ⟩ ⟩\n\n    a ≍˘ a\n┌─       \n╎ 0 1 2  \n  0 1 2  \n         \n  3 4 5  \n  3 4 5  \n         \n  6 7 8  \n  6 7 8  \n        ┘"
        }
    },
    "⚇": {
        "glyph": "⚇",
        "type": "2-modifier",
        "docUrl": "https://mlochbaum.github.io/BQN/help/depth.html",
        "monad": {
            "name": "Depth",
            "description": "Apply 𝔽 to the cells of the arguments at depth given in 𝕘. Negative numbers count down from the top level and non-negative ones from the bottom up.",
            "example": "1⊸↓⚇1 ⟨⟨1,2,3⟩, ⟨4,5,6⟩⟩\n⟨ ⟨ 2 3 ⟩ ⟨ 5 6 ⟩ ⟩\n\n    1 ↓⚇1 ⟨⟨1,2,3⟩, ⟨4,5,6⟩⟩\n⟨ ⟨ 2 3 ⟩ ⟨ 5 6 ⟩ ⟩\n\n    (+´↕)⚇0 ⟨2,4‿7,3⟩  # Implements pervasion\n⟨ 1 ⟨ 6 21 ⟩ 3 ⟩"
        }
    },
    "¨": {
        "glyph": "¨",
        "type": "1-modifier",
        "docUrl": "https://mlochbaum.github.io/BQN/help/each.html",
        "monad": {
            "name": "Each",
            "description": "Apply 𝔽 to/between the elements of the arguments. (𝔽⚇¯1)",
            "example": "<¨ 1‿2‿3\n┌─                   \n· ┌·    ┌·    ┌·     \n  · 1   · 2   · 3    \n      ┘     ┘     ┘  \n                    ┘\n\n    4‿5‿6 ∾¨ 1‿2‿3\n⟨ ⟨ 4 1 ⟩ ⟨ 5 2 ⟩ ⟨ 6 3 ⟩ ⟩"
        }
    },
    "⌜": {
        "glyph": "⌜",
        "type": "1-modifier",
        "docUrl": "https://mlochbaum.github.io/BQN/help/table.html",
        "monad": {
            "name": "Table",
            "description": "Apply 𝔽 between every possible pair of the elements of the arguments. Identical to Each when called with one argument.",
            "example": "1‿2‿3‿4 +⌜ 4‿5‿6‿7\n┌─           \n╵ 5 6  7  8  \n  6 7  8  9  \n  7 8  9 10  \n  8 9 10 11  \n            ┘\n\n    \"abc\" ∾⌜ \"xyz\"\n┌─                \n╵ \"ax\" \"ay\" \"az\"  \n  \"bx\" \"by\" \"bz\"  \n  \"cx\" \"cy\" \"cz\"  \n                 ┘"
        }
    },
    "⍟": {
        "glyph": "⍟",
        "type": "2-modifier",
        "docUrl": "https://mlochbaum.github.io/BQN/help/repeat.html",
        "monad": {
            "name": "Repeat",
            "description": "Apply 𝔾 to 𝕨 and 𝕩, then apply 𝔽 to 𝕩 that many times. If 𝕨 is given, use it each time as a constant left argument. If 𝔾 returns an array, give 𝔽⍟𝕩 for each of its elements.",
            "example": "1 +⍟⊢ 4\n8\n\n    1 +⍟1‿2‿3 4\n⟨ 5 6 7 ⟩\n\n    3 ∾⍟{≠𝕩} ⟨4,5,6⟩\n⟨ 3 3 3 4 5 6 ⟩"
        }
    },
    "⁼": {
        "glyph": "⁼",
        "type": "1-modifier",
        "docUrl": "https://mlochbaum.github.io/BQN/help/undo.html",
        "monad": {
            "name": "Undo",
            "description": "Invert the function 𝔽, or use its defined inverse. Not all functions have inverses.",
            "example": "1 - 2\n¯1\n\n    1 -⁼ 2\n¯1\n\n    √ 16\n4\n\n    √⁼ 4\n16\n\n    ⋆ 1\n2.718281828459045\n\n    ⋆⁼ 2.718281828459045\n1"
        }
    },
    "´": {
        "glyph": "´",
        "type": "1-modifier",
        "docUrl": "https://mlochbaum.github.io/BQN/help/fold.html",
        "monad": {
            "name": "Fold",
            "description": "Fold over 𝕩 with 𝔽 from right to left i.e. Insert 𝔽 between the elements of 𝕩. 𝕩 must be a simple list (1 = =𝕩).",
            "example": "+´ 1‿2‿3\n6\n\n    1+2+3\n6\n\n    -´ 1‿2‿3\n2\n\n    1-2-3\n2"
        },
        "dyad": {
            "name": "Fold With Initial",
            "description": "Monadic fold, but use 𝕨 as initial right argument.",
            "example": "5 +´ 1‿2‿3\n11\n\n    1+2+3+5\n11\n\n    5 -´ 1‿2‿3\n¯3\n\n    1-2-3-5\n¯3"
        }
    },
    "˝": {
        "glyph": "˝",
        "type": "1-modifier",
        "docUrl": "https://mlochbaum.github.io/BQN/help/insert.html",
        "monad": {
            "name": "Insert",
            "description": "Fold over cells of 𝕩 with 𝔽 from end to start, that is, insert 𝔽 between the major cells of 𝕩.",
            "example": "a ← 3‿3 ⥊ ↕9\n\n    +˝ a\n⟨ 9 12 15 ⟩\n\n    0‿1‿2 + 3‿4‿5 + 6‿7‿8\n⟨ 9 12 15 ⟩"
        },
        "dyad": {
            "name": "Insert With Initial",
            "description": "Monadic insert, but use 𝕨 as initial right argument.",
            "example": "b ← 3‿3 ⥊ ↕9\n\n    1‿1‿1 +˝ b\n⟨ 10 13 16 ⟩\n\n    1 +˝ b\n⟨ 10 13 16 ⟩\n\n    0‿1‿2 + 3‿4‿5 + 6‿7‿8 + 1‿1‿1\n⟨ 10 13 16 ⟩"
        }
    },
    "`": {
        "glyph": "`",
        "type": "1-modifier",
        "docUrl": "https://mlochbaum.github.io/BQN/help/scan.html",
        "monad": {
            "name": "Scan",
            "description": "Scan over 𝕩 with 𝔽 from left to right, producing intermediate values.",
            "example": "+` 1‿2‿3\n⟨ 1 3 6 ⟩\n\n    ⟨1, 1+2, (1+2)+3⟩\n⟨ 1 3 6 ⟩\n\n    -` 1‿2‿3\n⟨ 1 ¯1 ¯4 ⟩\n\n    ⟨1, 1-2, (1-2)-3⟩\n⟨ 1 ¯1 ¯4 ⟩"
        },
        "dyad": {
            "name": "Scan With initial",
            "description": "Monadic scan, but use 𝕨 as initial left argument.",
            "example": "5 +` 1‿2‿3\n⟨ 6 8 11 ⟩\n\n    ⟨5+1, (5+1)+2, ((5+1)+2)+3⟩\n⟨ 6 8 11 ⟩\n\n    5 -` 1‿2‿3\n⟨ 4 2 ¯1 ⟩\n\n    ⟨5-1, (5-1)-2, ((5-1)-2)-3⟩\n⟨ 4 2 ¯1 ⟩"
        }
    },
    "←": {
        "glyph": "←",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/define.html",
        "monad": {
            "name": "Define",
            "description": "",
            "example": null
        }
    },
    "⇐": {
        "glyph": "⇐",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/export.html",
        "monad": {
            "name": "Export Definition",
            "description": "",
            "example": null
        },
        "dyad": {
            "name": "Export names",
            "description": "Define a variable with name n and export it from the current namespace.",
            "example": "ns ← { exported ⇐ 5, unexported ← 0}\n    ns.exported\n5\n    ns.unexported\nError: Field named \"unexported\" not found"
        }
    },
    "↩": {
        "glyph": "↩",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/change.html",
        "monad": {
            "name": "Change",
            "description": "",
            "example": null
        },
        "dyad": {
            "name": "Modify",
            "description": "Changes the value of variable with name n to value v. Variable n must already exist.",
            "example": "a ↩ 1\nError: Undefined identifier\n\n    ⊢ b ← 3\n3\n\n    ⊢ b ↩ \"Be the change you wish to see in the world.\"\n\"Be the change you wish to see in the world.\""
        }
    },
    "⋄": {
        "glyph": "⋄",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/separator.html",
        "monad": {
            "name": "Separator",
            "description": "",
            "example": null
        }
    },
    ".": {
        "glyph": ".",
        "type": "function",
        "docUrl": "https://mlochbaum.github.io/BQN/help/namespacefield.html",
        "monad": {
            "name": "Namespace Field",
            "description": "",
            "example": null
        }
    },
    "(": {
        "glyph": "(",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/beginexpression.html",
        "monad": {
            "name": "Begin Expression",
            "description": "",
            "example": null
        }
    },
    ")": {
        "glyph": ")",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/endexpression.html",
        "monad": {
            "name": "End Expression",
            "description": "",
            "example": null
        }
    },
    "{": {
        "glyph": "{",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/beginblock.html",
        "monad": {
            "name": "Begin Block",
            "description": "",
            "example": null
        }
    },
    "}": {
        "glyph": "}",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/endblock.html",
        "monad": {
            "name": "End Block",
            "description": "",
            "example": null
        }
    },
    ";": {
        "glyph": ";",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/nextbody.html",
        "monad": {
            "name": "Next Body",
            "description": "",
            "example": null
        }
    },
    ":": {
        "glyph": ":",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/header.html",
        "monad": {
            "name": "Header",
            "description": "",
            "example": null
        }
    },
    "?": {
        "glyph": "?",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/predicate.html",
        "monad": {
            "name": "Predicate",
            "description": "",
            "example": null
        }
    },
    "⟨": {
        "glyph": "⟨",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/beginlist.html",
        "monad": {
            "name": "Begin list",
            "description": "",
            "example": null
        }
    },
    "⟩": {
        "glyph": "⟩",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/endlist.html",
        "monad": {
            "name": "End list",
            "description": "",
            "example": null
        }
    },
    "[": {
        "glyph": "[",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/beginarray.html",
        "monad": {
            "name": "Begin array",
            "description": "",
            "example": null
        }
    },
    "]": {
        "glyph": "]",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/endarray.html",
        "monad": {
            "name": "End array",
            "description": "",
            "example": null
        }
    },
    "‿": {
        "glyph": "‿",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/strand.html",
        "monad": {
            "name": "Strand",
            "description": "",
            "example": null
        }
    },
    "·": {
        "glyph": "·",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/nothing.html",
        "monad": {
            "name": "Nothing",
            "description": "",
            "example": null
        }
    },
    "•": {
        "glyph": "•",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/system.html",
        "monad": {
            "name": "System",
            "description": "",
            "example": null
        }
    },
    "𝕨": {
        "glyph": "𝕨",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/leftargument.html",
        "monad": {
            "name": "Left Argument",
            "description": "",
            "example": null
        }
    },
    "𝕩": {
        "glyph": "𝕩",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/rightargument.html",
        "monad": {
            "name": "Right Argument",
            "description": "A variable assigned to the right argument of a block. 𝕏 can be used to access the right argument as a function.",
            "example": "5 {𝕩} 1\n1"
        }
    },
    "𝔽": {
        "glyph": "𝔽",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/modifierleftoperand.html",
        "monad": {
            "name": "Modifier Left operand",
            "description": "",
            "example": null
        }
    },
    "𝔾": {
        "glyph": "𝔾",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/2-modifierrightoperand.html",
        "monad": {
            "name": "2-Modifier Right operand",
            "description": "",
            "example": null
        }
    },
    "𝕊": {
        "glyph": "𝕊",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/currentfunction.html",
        "monad": {
            "name": "Current Function",
            "description": "",
            "example": null
        }
    },
    "𝕣": {
        "glyph": "𝕣",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/currentmodifier.html",
        "monad": {
            "name": "Current Modifier",
            "description": "",
            "example": null
        }
    },
    "¯": {
        "glyph": "¯",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/minus.html",
        "monad": {
            "name": "Minus",
            "description": "",
            "example": null
        }
    },
    "π": {
        "glyph": "π",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/pi.html",
        "monad": {
            "name": "Pi",
            "description": "",
            "example": null
        }
    },
    "∞": {
        "glyph": "∞",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/infinity.html",
        "monad": {
            "name": "Infinity",
            "description": "",
            "example": null
        }
    },
    "@": {
        "glyph": "@",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/nullcharacter.html",
        "monad": {
            "name": "Null Character",
            "description": "",
            "example": null
        }
    },
    "#": {
        "glyph": "#",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/comment.html",
        "monad": {
            "name": "Comment",
            "description": "",
            "example": null
        }
    },
    "'": {
        "glyph": "'",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/character.html",
        "monad": {
            "name": "Character",
            "description": "",
            "example": null
        }
    },
    "\"": {
        "glyph": "\"",
        "type": "syntax",
        "docUrl": "https://mlochbaum.github.io/BQN/help/string.html",
        "monad": {
            "name": "String",
            "description": "",
            "example": null
        }
    }
};

/**
 * Get formatted hover content for a BQN glyph
 * 
 * @param {string} glyph - The primitive glyph
 * @returns {Object|null} Formatted hover content or null if not found
 */
export function getBqnHoverContent(glyph) {
    const doc = bqnGlyphDocs[glyph];
    if (!doc) return null;
    
    return {
        glyph: doc.glyph,
        type: doc.type,
        title: doc.name,
        description: doc.description,
        example: doc.example,
        docUrl: doc.docUrl,
    };
}

export default bqnGlyphDocs;
