/**
 * J Language Primitive Documentation
 * 
 * Auto-generated by scripts/scrape-j-docs.cjs
 * Source: https://code.jsoftware.com/wiki/NuVoc
 * Generated: 2026-01-28T13:09:33.978Z
 * 
 * Run `node scripts/scrape-j-docs.cjs` to update from upstream docs.
 * 
 * LICENSE ATTRIBUTION:
 * The documentation content in this file is derived from the J Wiki (NuVoc).
 * Source: https://code.jsoftware.com/wiki/NuVoc
 * License: Creative Commons Attribution-ShareAlike
 * See THIRD_PARTY_LICENSES.md for full license text.
 */

export const jDocsMeta = {
    "language": "J",
    "source": "https://code.jsoftware.com/wiki/NuVoc",
    "scrapedAt": "2026-01-28T13:09:33.978Z",
    "version": "1.0.0"
};

export const jGlyphDocs = {
    "=": {
        "glyph": "=",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/eq",
        "monad": {
            "name": "Self-Classify",
            "description": "A Boolean table relating a given vector to its Nub (~.)."
        },
        "dyad": {
            "name": "Equal",
            "description": "The Boolean result of comparing x and y atom by atom."
        }
    },
    "<": {
        "glyph": "<",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/lt",
        "monad": {
            "name": "Box",
            "description": "Convert the noun y to boxed form, by creating a box whose contents are y. A box is treated as an atom and can be put into an array with other boxes, regardless of the contents of the boxes."
        },
        "dyad": {
            "name": "Less Than",
            "description": "Compares x and y atom-by-atom. See Equal (=) for the details."
        }
    },
    "<.": {
        "glyph": "<.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/ltdot",
        "monad": {
            "name": "Floor",
            "description": "The floor of y i.e. the largest integer less than or equal to y"
        },
        "dyad": {
            "name": "Lesser Of (Min)",
            "description": "The lesser atoms of x and y"
        }
    },
    "<:": {
        "glyph": "<:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/ltco",
        "monad": {
            "name": "Decrement",
            "description": "Equivalent to y-1"
        },
        "dyad": {
            "name": "Less Or Equal",
            "description": "Compares x and y atom-by-atom. See Equal (=) for the details."
        }
    },
    ">": {
        "glyph": ">",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/gt",
        "monad": {
            "name": "Open",
            "description": "Opens (undoes the boxing) of a boxed element or array of boxed elements."
        },
        "dyad": {
            "name": "Greater Than",
            "description": "Compares x and y atom-by-atom. See Equal (=) for the details."
        }
    },
    ">.": {
        "glyph": ">.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/gtdot",
        "monad": {
            "name": "Ceiling",
            "description": "The ceiling of y i.e. the smallest integer greater than or equal to y"
        },
        "dyad": {
            "name": "Greater Of (Max)",
            "description": "The larger atoms of x and y"
        }
    },
    ">:": {
        "glyph": ">:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/gtco",
        "monad": {
            "name": "Increment",
            "description": "Equivalent to y+1."
        },
        "dyad": {
            "name": "Greater Or Equal",
            "description": "Compares x and y atom-by-atom. See Equal (=) for the details."
        }
    },
    "+": {
        "glyph": "+",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/plus",
        "monad": {
            "name": "Conjugate",
            "description": "The complex conjugate of the number y"
        },
        "dyad": {
            "name": "Plus",
            "description": "Adds two numeric nouns: x and y"
        }
    },
    "+.": {
        "glyph": "+.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/plusdot",
        "monad": {
            "name": "Real/Imag",
            "description": "Decomposes complex numbers into real and imaginary parts"
        },
        "dyad": {
            "name": "GCD (Or)",
            "description": "The logical operation Or between two Boolean nouns x and y."
        }
    },
    "+:": {
        "glyph": "+:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/plusco",
        "monad": {
            "name": "Double",
            "description": "Equivalent to 2 * y."
        },
        "dyad": {
            "name": "Not-Or",
            "description": "The logical operation Not-Or between two Boolean nouns x and y, which is 0 (false) if x or y is 1 (true)."
        }
    },
    "*": {
        "glyph": "*",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/star",
        "monad": {
            "name": "Signum",
            "description": "The sign of the number y"
        },
        "dyad": {
            "name": "Times",
            "description": "The product of two numeric nouns, x and y"
        }
    },
    "*.": {
        "glyph": "*.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/stardot",
        "monad": {
            "name": "Length/Angle",
            "description": "Converts x-y coordinates (given as a complex number) to r-theta coordinates (\"theta\" being in radians). The angle is in the range (-π,π]"
        },
        "dyad": {
            "name": "LCM (And)",
            "description": "The logical operation And between two Boolean nouns x and y."
        }
    },
    "*:": {
        "glyph": "*:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/starco",
        "monad": {
            "name": "Square",
            "description": "Equivalent to y ^ 2, the square of numeric noun y."
        },
        "dyad": {
            "name": "Not-And",
            "description": "The logical operation Not-And between two Boolean nouns x and y, which is false (0) if x and y are both true (1)."
        }
    },
    "-": {
        "glyph": "-",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/minus",
        "monad": {
            "name": "Negate",
            "description": "Negates value of number y"
        },
        "dyad": {
            "name": "Minus",
            "description": "Subtracts the value of y from x"
        }
    },
    "-.": {
        "glyph": "-.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/minusdot",
        "monad": {
            "name": "Not",
            "description": "Equivalent to 1 - y ."
        },
        "dyad": {
            "name": "Less",
            "description": "When x and y are lists, x -. y is all the atoms of x that are not in y, preserving the original order in x. (A-.B) has the following Venn diagram"
        }
    },
    "-:": {
        "glyph": "-:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/minusco",
        "monad": {
            "name": "Halve",
            "description": "Equivalent to y % 2 (y divided by 2)."
        },
        "dyad": {
            "name": "Match",
            "description": "Returns a boolean value, 1 if and only if x is the same as y in shape and elements. Tolerant comparison is used whenever numeric types are compared; use -:!.0 to force exact comparison."
        }
    },
    "%": {
        "glyph": "%",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/percent",
        "monad": {
            "name": "Reciprocal",
            "description": "Equivalent to 1 % y, the reciprocal of the number y"
        },
        "dyad": {
            "name": "Divide",
            "description": "x divided by y"
        }
    },
    "%.": {
        "glyph": "%.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/percentdot",
        "monad": {
            "name": "Matrix Inverse",
            "description": "The inverse matrix of square matrix y, denoted y^-1^"
        },
        "dyad": {
            "name": "Matrix Divide",
            "description": "x %. y is (%. y) mux x where mux denotes matrix multiplication."
        }
    },
    "%:": {
        "glyph": "%:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/percentco",
        "monad": {
            "name": "Square Root",
            "description": "The square root of y ."
        },
        "dyad": {
            "name": "Root",
            "description": "The x-th root of y ."
        }
    },
    "^": {
        "glyph": "^",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/hat",
        "monad": {
            "name": "Exponential",
            "description": "ey, the y-th power of the mathematical constant: e ."
        },
        "dyad": {
            "name": "Power",
            "description": "xy, the y-th power of numeric noun: x ."
        }
    },
    "^.": {
        "glyph": "^.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/hatdot",
        "monad": {
            "name": "Natural Log",
            "description": "ln ⁡ y {\\displaystyle \\ln y} or log e ⁡ y {\\displaystyle \\log _{e}y} - the natural logarithm of y ."
        },
        "dyad": {
            "name": "Logarithm",
            "description": "The logarithm of y to the base x ."
        }
    },
    "$": {
        "glyph": "$",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/dollar",
        "monad": {
            "name": "Shape Of",
            "description": "The shape of the noun y ."
        },
        "dyad": {
            "name": "Shape",
            "description": "Creates an array whose shape depends on x and the shape of y. $ uses items of y; ($,) uses atoms of y;"
        }
    },
    "$.": {
        "glyph": "$.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/dollardot",
        "monad": {
            "name": "Sparse",
            "description": "Gives a noun that can replace (numeric) y in working code, with only the non-zero atoms of $.y stored in memory. See the entry in the J Dictionary for details"
        },
        "dyad": {
            "name": "Sparse",
            "description": "n&$. is a collection of functions for creating and handling sparse arrays and converting them to/from ordinary arrays."
        }
    },
    "~.": {
        "glyph": "~.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/tildedot",
        "monad": {
            "name": "Nub",
            "description": "Removes duplicates from a list."
        }
    },
    "~:": {
        "glyph": "~:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/tildeco",
        "monad": {
            "name": "Nub Sieve",
            "description": "A Boolean vector with one value per item of y . Which is 1 if the item does not match any previous item."
        },
        "dyad": {
            "name": "Not-Equal",
            "description": "The Boolean result of comparing two items, or lists of items, atom by atom."
        }
    },
    "|": {
        "glyph": "|",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/bar",
        "monad": {
            "name": "Magnitude",
            "description": "The absolute value of numeric y. If y is complex, |y is the magnitude of y."
        },
        "dyad": {
            "name": "Residue",
            "description": "The remainder when dividing a given number y by another given number x."
        }
    },
    "|.": {
        "glyph": "|.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/bardot",
        "monad": {
            "name": "Reverse",
            "description": "Rearranges the items of y in reverse order"
        },
        "dyad": {
            "name": "Rotate",
            "description": "Rotates the items of y leftwards or upwards x positions. See below for Shift instead of Rotate."
        }
    },
    "|:": {
        "glyph": "|:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/barco",
        "monad": {
            "name": "Transpose",
            "description": "Reverses the axes of an array y"
        },
        "dyad": {
            "name": "Rearrange Axes",
            "description": "Rearranges the axes of an array y."
        }
    },
    ",": {
        "glyph": ",",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/comma",
        "monad": {
            "name": "Ravel",
            "description": "Produces a list containing all the atoms in y, in the order in which they appear in the display of y."
        },
        "dyad": {
            "name": "Append",
            "description": "Creates an array containing the items of x followed by the items of y ."
        }
    },
    ",.": {
        "glyph": ",.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/commadot",
        "monad": {
            "name": "Ravel Items",
            "description": "Creates a table where each row of the table comes from an item of y."
        },
        "dyad": {
            "name": "Stitch",
            "description": "Joins each item of x to the corresponding item of y"
        }
    },
    ",:": {
        "glyph": ",:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/commaco",
        "monad": {
            "name": "Itemize",
            "description": "Creates an array whose rank is 1 more than the rank of y, and whose single item is y ."
        },
        "dyad": {
            "name": "Laminate",
            "description": "Creates a two-item array (with rank at least 2) whose first item comes from x and whose second item comes from y ."
        }
    },
    ";": {
        "glyph": ";",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/semi",
        "monad": {
            "name": "Raze",
            "description": "Removes one level of boxing from a noun. Cells of the contents of each box then become the items of the result."
        },
        "dyad": {
            "name": "Link",
            "description": "Links x and y to build up a list of boxed items."
        }
    },
    ";:": {
        "glyph": ";:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/semico",
        "monad": {
            "name": "Words",
            "description": "Partitions a string into boxed words according to J's rules for word formation."
        },
        "dyad": {
            "name": "Sequential Machine",
            "description": "Partitions a string (or a more general kind of list) y according to the rules of a given finite-state (Mealy) machine defined by noun x."
        }
    },
    "#": {
        "glyph": "#",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/number",
        "monad": {
            "name": "Tally",
            "description": "Counts the items in y"
        },
        "dyad": {
            "name": "Copy",
            "description": "Creates a new array in which each integer in x controls how many times the corresponding item of y appears"
        }
    },
    "#.": {
        "glyph": "#.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/numberdot",
        "monad": {
            "name": "Base 2",
            "description": "The corresponding number of a binary numeral, given as a Boolean list"
        },
        "dyad": {
            "name": "Base",
            "description": "Generalizes #.y to bases other than 2 (including mixed bases)"
        }
    },
    "#:": {
        "glyph": "#:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/numberco",
        "monad": {
            "name": "Antibase 2",
            "description": "Returns the binary expansion of a given number y as a Boolean list"
        },
        "dyad": {
            "name": "Antibase",
            "description": "Generalizes the action of (#: y) to other bases than 2 (including mixed bases)"
        }
    },
    "!": {
        "glyph": "!",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/bang",
        "monad": {
            "name": "Factorial",
            "description": "The Factorial of y."
        },
        "dyad": {
            "name": "Out Of (Binomial)",
            "description": "Returns y-Combinations-x: yCx (read: x out of y or: y pick x)."
        }
    },
    "[": {
        "glyph": "[",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/squarelf",
        "monad": {
            "name": "Same",
            "description": "Returns noun y unchanged: [y is equivalent to y."
        },
        "dyad": {
            "name": "Left",
            "description": "Returns the (noun) value of x"
        }
    },
    "]": {
        "glyph": "]",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/squarert",
        "monad": {
            "name": "Same",
            "description": "Returns noun y unchanged, i.e. (]y) is equivalent to y."
        },
        "dyad": {
            "name": "Right",
            "description": "Returns the (noun) value of y -- ignoring x"
        }
    },
    "{": {
        "glyph": "{",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/curlylf",
        "monad": {
            "name": "Catalogue",
            "description": "Combines items from the atoms inside a boxed list to form a catalogue."
        },
        "dyad": {
            "name": "From",
            "description": "Selects the item with index x from the array y . Negative values of x count back from the end of the array, which is item number _1."
        }
    },
    "{.": {
        "glyph": "{.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/curlylfdot",
        "monad": {
            "name": "Head",
            "description": "The leading item of y"
        },
        "dyad": {
            "name": "Take",
            "description": "The leading x items of y."
        }
    },
    "{:": {
        "glyph": "{:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/curlylfco",
        "monad": {
            "name": "Tail",
            "description": "The last item of y"
        }
    },
    "{::": {
        "glyph": "{::",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/curlylfcoco",
        "monad": {
            "name": "Map",
            "description": "A map of the boxed noun y i.e. a noun having the same box structure as y but with each leaf replaced by the path to that leaf."
        },
        "dyad": {
            "name": "Fetch",
            "description": "A list of the contents of selected boxes in a boxed noun: y"
        }
    },
    "}": {
        "glyph": "}",
        "type": "adverb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/curlyrt",
        "monad": {
            "name": "Item Amend",
            "description": "Create an array having the shape of an item of y that's a composite of the items of y."
        },
        "dyad": {
            "name": "Amend",
            "description": "x m} y amends y by creating a new noun that is a copy of y with the locations m replaced by new values x"
        }
    },
    "}.": {
        "glyph": "}.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/curlyrtdot",
        "monad": {
            "name": "Behead",
            "description": "Drop the leading item from y"
        },
        "dyad": {
            "name": "Drop",
            "description": "Drop the leading x items of y"
        }
    },
    "}:": {
        "glyph": "}:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/curlyrtco",
        "monad": {
            "name": "Curtail",
            "description": "Drops the last item from y"
        }
    },
    "?": {
        "glyph": "?",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/query",
        "monad": {
            "name": "Roll",
            "description": "Generates a random number uniformly distributed in a range determined by integer y."
        },
        "dyad": {
            "name": "Deal",
            "description": "Selects x items at random (without repetition) from the list i.y"
        }
    },
    "?.": {
        "glyph": "?.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/querydot",
        "monad": {
            "name": "Roll (fixed seed)",
            "description": "1. (?.) uses RNG 1, GB_Flip."
        },
        "dyad": {
            "name": "Deal (fixed seed)",
            "description": "Behaves like Roll/Deal (?) — except that the random-number generator (RNG) is reset each time ?. is executed."
        }
    },
    "i.": {
        "glyph": "i.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/idot",
        "monad": {
            "name": "Integers",
            "description": "Returns an ascending (or descending) sequence of integers, wrapped to the shape specified by (|y)."
        },
        "dyad": {
            "name": "Index Of",
            "description": "Finds the first occurrence of y in x"
        }
    },
    "i:": {
        "glyph": "i:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/ico",
        "monad": {
            "name": "Steps",
            "description": "Like Integers (i.), except that the sequence ranges from (-y) thru (+y)."
        },
        "dyad": {
            "name": "Index Of Last",
            "description": "Like Index Of (i.), except that it finds the last occurrence not the first."
        }
    },
    "I.": {
        "glyph": "I.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/icapdot",
        "monad": {
            "name": "Indices",
            "description": "The indexes of every 1 in the Boolean list y"
        },
        "dyad": {
            "name": "Interval Index",
            "description": "x must be in sorted order, and thus defines (1+#x) intervals, where each interval but the last ends on an item of x (inclusive) and the last interval ends at infinity."
        }
    },
    "j.": {
        "glyph": "j.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/jdot",
        "monad": {
            "name": "Imaginary",
            "description": "Multiplies y by 0j1, which represents the imaginary unit i ."
        },
        "dyad": {
            "name": "Complex",
            "description": "Combines x and y into a complex number having x as its real part and y as its imaginary part"
        }
    },
    "o.": {
        "glyph": "o.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/odot",
        "monad": {
            "name": "Pi Times",
            "description": "Returns (π times y) given any number y ."
        },
        "dyad": {
            "name": "Circle Function",
            "description": "Combines the common trigonometric and hyperbolic functions, and their inverses, without the need for reserved words like sin, cos, etc."
        }
    },
    "p.": {
        "glyph": "p.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/pdot",
        "monad": {
            "name": "Roots",
            "description": "Converts the polynomial y between coefficient and multiplier-and-roots form."
        },
        "dyad": {
            "name": "Polynomial",
            "description": "Evaluates polynomial x for given value(s) of y."
        }
    },
    "p:": {
        "glyph": "p:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/pco",
        "monad": {
            "name": "Primes",
            "description": "The y-th prime (starting with 2 as the 0-th prime)."
        }
    },
    "q:": {
        "glyph": "q:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/qco",
        "monad": {
            "name": "Prime Factors",
            "description": "The prime factorization of integer y, listed in ascending order."
        },
        "dyad": {
            "name": "Prime Exponents",
            "description": "Selected primes and their exponents in the factorization of y."
        }
    },
    "r.": {
        "glyph": "r.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/rdot",
        "monad": {
            "name": "Angle",
            "description": "The angle y (in radians), expressed as a unit vector in the complex plane"
        },
        "dyad": {
            "name": "Polar",
            "description": "Like monadic (r.), but with a scaling factor x"
        }
    },
    "x:": {
        "glyph": "x:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/xco",
        "monad": {
            "name": "Extended Precision",
            "description": "Converts number y to extended precision, either extended integer or rational."
        }
    },
    "A.": {
        "glyph": "A.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/acapdot",
        "monad": {
            "name": "Anagram Index",
            "description": "A. y converts the permutation y into its permutation number (also called its anagram index)."
        },
        "dyad": {
            "name": "Anagram",
            "description": "x A. y reorders the items of y by applying the permutation of length #y whose permutation number is x."
        }
    },
    "C.": {
        "glyph": "C.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/ccapdot",
        "monad": {
            "name": "Cycle-Direct",
            "description": "Converts the permutation y between direct and cycle representations."
        },
        "dyad": {
            "name": "Permute",
            "description": "Applies the permutation x to the items of y."
        }
    },
    "e.": {
        "glyph": "e.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/edot",
        "monad": {
            "name": "Raze In",
            "description": "Returns a Boolean table comparing each box of y (a list of boxed atoms) against each atom in ;y (the Raze of y)."
        },
        "dyad": {
            "name": "Member (In)",
            "description": "Returns 1 if item x is in array y, otherwise 0."
        }
    },
    "E.": {
        "glyph": "E.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/ecapdot",
        "dyad": {
            "name": "Find Matches",
            "description": "Create a Boolean array indicating starting points in y of subarrays equal to x."
        }
    },
    "L.": {
        "glyph": "L.",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/lcapdot",
        "monad": {
            "name": "Level Of",
            "description": "The greatest level of nesting of a boxed noun, or 0 if unboxed."
        }
    },
    "s:": {
        "glyph": "s:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/sco",
        "monad": {
            "name": "Symbol",
            "description": "A symbol is an atom of a special type that stands for a list of characters. A symbol is an alternative to a boxed string."
        },
        "dyad": {
            "name": "Symbol",
            "description": "A collection of verbs for working with symbol sets (see above). The choice of verb is determined by the values of x and y."
        }
    },
    "u:": {
        "glyph": "u:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/uco",
        "monad": {
            "name": "Unicode",
            "description": "The unicode character corresponding to y."
        },
        "dyad": {
            "name": "Unicode",
            "description": "Converts between numbers, character precisions and encodings according to the Unicode and UTF-8 standards."
        }
    },
    "~": {
        "glyph": "~",
        "type": "adverb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/tilde",
        "monad": {
            "name": "Reflex",
            "description": "(u~ y) is the same as (y u y)"
        },
        "dyad": {
            "name": "Passive",
            "description": "Rank -- depends on the rank of u -- WHY IS THIS IMPORTANT?"
        }
    },
    "/": {
        "glyph": "/",
        "type": "adverb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/slash",
        "monad": {
            "name": "Insert",
            "description": "Inserts dyad u between the items of y"
        },
        "dyad": {
            "name": "Table",
            "description": "(x u/ y) returns a table having entries (a u b) for every a in x and b in y"
        }
    },
    "/.": {
        "glyph": "/.",
        "type": "adverb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/slashdot",
        "monad": {
            "name": "Oblique",
            "description": "(u/.y) applies verb u to the oblique diagonals of table y"
        },
        "dyad": {
            "name": "Key",
            "description": "Classifies items of x into partitions of identical items. Then y is partitioned using the partitioning that was calculated for x, and u is applied on each partition of y."
        }
    },
    "/:": {
        "glyph": "/:",
        "type": "adverb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/slashco",
        "monad": {
            "name": "Grade Up",
            "description": "The permutation that sorts the items of y into ascending (/:) or descending (\\:) order (numerical or lexicographical)"
        },
        "dyad": {
            "name": "Sort Up",
            "description": "Sorts x using the order given by y."
        }
    },
    "\\": {
        "glyph": "\\",
        "type": "adverb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/bslash",
        "monad": {
            "name": "Prefix",
            "description": "(u\\y) applies verb u to successive prefixes of list y of increasing length (1, 2, 3, ...)"
        },
        "dyad": {
            "name": "Infix",
            "description": "(x u\\y) applies verb u to successive parts of list y (called infixes)."
        }
    },
    "\\.": {
        "glyph": "\\.",
        "type": "adverb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/bslashdot",
        "monad": {
            "name": "Suffix",
            "description": "(u\\. y) applies verb u to successive suffixes of list y of decreasing length"
        },
        "dyad": {
            "name": "Outfix",
            "description": "(x u\\. y) applies verb u to successive outfixes of y. Each outfix is y with an infix removed. The infixes depend on x, as described in Infix (\\)."
        }
    },
    "\\:": {
        "glyph": "\\:",
        "type": "adverb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/bslashco",
        "monad": {
            "name": "Grade Down",
            "description": "The permutation that sorts list y into descending order (numerical or lexicographical)"
        },
        "dyad": {
            "name": "Sort Down",
            "description": "Applies to list x the permutation that sorts list y into descending order (numerical or lexicographical)"
        }
    },
    "b.": {
        "glyph": "b.",
        "type": "adverb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/bdot",
        "monad": {
            "name": "Boolean/Bitwise",
            "description": "Creates a verb to perform logic on the bit(s) of y (and x, if present)."
        }
    },
    "f.": {
        "glyph": "f.",
        "type": "adverb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/fdot",
        "monad": {
            "name": "Fix",
            "description": "Fixes tacit verb u (i.e. gives it a fixed value without name dependencies) by replacing each name in u with the fixed value of the name. Similarly, m f. replaces each name in the entity denoted by character array m with the fixed value of the name. See below for an example."
        }
    },
    "M.": {
        "glyph": "M.",
        "type": "adverb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/mcapdot",
        "monad": {
            "name": "Memo",
            "description": "u M. is identical in function to verb u, except that it might be faster if u is highly recursive."
        }
    },
    "t.": {
        "glyph": "t.",
        "type": "adverb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/tdot",
        "monad": {
            "name": "Run as Task",
            "description": "[x] u t. n y runs ([x] <@:u y) in an idle thread and returns its result, which is a pyx. A pyx is a special box. It looks like an atomic box and can be used like any other box. When the pyx is opened, the opening thread will block until the value is available. If the creation of the pyx ended in ..."
        }
    },
    "^:": {
        "glyph": "^:",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/hatco",
        "monad": {
            "name": "Power (of verb)",
            "description": "Described below."
        }
    },
    ".": {
        "glyph": ".",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/dot",
        "monad": {
            "name": "Determinant",
            "description": "-/ . * y is the determinant of square matrix y ."
        },
        "dyad": {
            "name": "Dot Product",
            "description": "x +/ . * y is the inner product or matrix product of matrices x and y."
        }
    },
    ":": {
        "glyph": ":",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/cor",
        "monad": {
            "name": "Explicit",
            "description": "Defines all types of entities."
        },
        "dyad": {
            "name": "Explicit",
            "description": "Defines all types of entities."
        }
    },
    ":.": {
        "glyph": ":.",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/codot",
        "monad": {
            "name": "Obverse",
            "description": "Under (Dual) (u&.v), Under (Dual) (u&.:v)"
        }
    },
    "::": {
        "glyph": "::",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/coco",
        "monad": {
            "name": "Adverse",
            "description": "Provides an alternative verb v to be run if the verb u failsIf the right operand of :: is a noun n, it is equivalent to the constant verb (n\"_) which ignores its arguments and produces the result n."
        }
    },
    ";.": {
        "glyph": ";.",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/semidot",
        "monad": {
            "name": "Cut",
            "description": "A collection of 3 adverbs, collectively known as Cut, with different syntax and semantics."
        },
        "dyad": {
            "name": "Cut",
            "description": "A collection of 3 adverbs, collectively known as Cut, with different syntax and semantics."
        }
    },
    "!.": {
        "glyph": "!.",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/bangdot",
        "monad": {
            "name": "Fit",
            "description": "The customized verb u!.n is a predetermined variant of primitive verb u according to the (noun) operand n."
        }
    },
    "!:": {
        "glyph": "!:",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/bangco",
        "monad": {
            "name": "Foreign",
            "description": "Generates entities (the so-called Foreigns). Almost all of these entities are verbs which perform such tasks as:"
        }
    },
    "\"": {
        "glyph": "\"",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/quote",
        "monad": {
            "name": "Rank",
            "description": "Explanation of the verb cross\"0 0\"0 1 :"
        }
    },
    "\".": {
        "glyph": "\".",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/quotedot",
        "monad": {
            "name": "Do",
            "description": "Executes the sentence y, returning the result of the sentence as the result of \". y. y is a list of characters."
        },
        "dyad": {
            "name": "Numbers",
            "description": "Converts a byte array y into numbers."
        }
    },
    "\":": {
        "glyph": "\":",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/quoteco",
        "monad": {
            "name": "Default Format",
            "description": "Converts y to an array of bytes, converting non-character types to displayable form."
        },
        "dyad": {
            "name": "Format",
            "description": "Converts y to a byte array formatted according to the specification x"
        }
    },
    "`": {
        "glyph": "`",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/grave",
        "monad": {
            "name": "Tie (Gerund)",
            "description": "u`v creates a list of gerunds for u and v — nouns that encode the verb values."
        }
    },
    "`:": {
        "glyph": "`:",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/graveco",
        "monad": {
            "name": "Evoke Gerund",
            "description": "If m is a gerund, m`:n creates a verb based on m."
        }
    },
    "@": {
        "glyph": "@",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/at",
        "monad": {
            "name": "Atop",
            "description": "u@v is equivalent to (u@:v)\"v. That is,"
        },
        "dyad": {
            "name": "Atop",
            "description": "u@v is equivalent to (u@:v)\"v. That is,"
        }
    },
    "@.": {
        "glyph": "@.",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/atdot",
        "monad": {
            "name": "Agenda",
            "description": "1. All of the ARs in the agenda must define verbs."
        }
    },
    "@:": {
        "glyph": "@:",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/atco",
        "monad": {
            "name": "At",
            "description": "Forms the composition of two verbs u and v ."
        },
        "dyad": {
            "name": "At",
            "description": "Forms the composition of two verbs u and v ."
        }
    },
    "&": {
        "glyph": "&",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/ampm",
        "monad": {
            "name": "Bond",
            "description": "1. Weld a noun to a verb, creating a unit that bypasses processing by other modifiers. To prefix 'Mr. ' to each boxed string:"
        },
        "dyad": {
            "name": "Compose",
            "description": "1. Weld a noun to a verb, creating a unit that bypasses processing by other modifiers. To prefix 'Mr. ' to each boxed string:"
        }
    },
    "&.": {
        "glyph": "&.",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/ampdot",
        "monad": {
            "name": "Under (Dual)",
            "description": "The operation encapsulated by u&.v is used often and is important as a notation to aid thought. When the operation is dyadic, sometimes the sequence of transforming/operating/transforming back should be applied to just one argument, with the other argument being passed unchanged into u. This can ..."
        }
    },
    "&.:": {
        "glyph": "&.:",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/ampdotco",
        "monad": {
            "name": "Under",
            "description": "Executes v on the argument(s); then executes u on the result(s) of v; then executes v^:_1 (i.e. the obverse of v) on the result of u, giving the end result. We say that u is applied under v."
        }
    },
    "&:": {
        "glyph": "&:",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/ampco",
        "monad": {
            "name": "Appose",
            "description": "Applies verb v to each argument, and then applies verb u dyadically between the result(s)."
        }
    },
    "d.": {
        "glyph": "d.",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/ddot",
        "monad": {
            "name": "Derivative",
            "description": "The ordinary n-th derivative of [the mathematical function implemented by] verb u."
        }
    },
    "D.": {
        "glyph": "D.",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/dcapdot",
        "monad": {
            "name": "Derivative",
            "description": "1. Generating higher-order partial derivatives with D. 2 fails. Use repeated application of D. 1 instead."
        }
    },
    "D:": {
        "glyph": "D:",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/dcapco",
        "monad": {
            "name": "Secant Slope",
            "description": "The slope of a straight line drawn through point y and point y+x on the curve of the mathematical function [implemented by verb] u"
        }
    },
    "F.": {
        "glyph": "F.",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/fcap",
        "monad": {
            "name": "Fold",
            "description": "All limited Folds can be thought of as variants of Fold Multiple Forward (F:.). Therefore F:. will be discussed first, and differences in the other Fold variants will be discussed with respect to F:. ."
        },
        "dyad": {
            "name": "Fold",
            "description": "1. Write a while loop without introducing special syntax or control words."
        }
    },
    "F..": {
        "glyph": "F..",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/fcap",
        "monad": {
            "name": "Fold",
            "description": "All limited Folds can be thought of as variants of Fold Multiple Forward (F:.). Therefore F:. will be discussed first, and differences in the other Fold variants will be discussed with respect to F:. ."
        },
        "dyad": {
            "name": "Fold",
            "description": "1. Write a while loop without introducing special syntax or control words."
        }
    },
    "F.:": {
        "glyph": "F.:",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/fcap",
        "monad": {
            "name": "Fold",
            "description": "All limited Folds can be thought of as variants of Fold Multiple Forward (F:.). Therefore F:. will be discussed first, and differences in the other Fold variants will be discussed with respect to F:. ."
        },
        "dyad": {
            "name": "Fold",
            "description": "1. Write a while loop without introducing special syntax or control words."
        }
    },
    "F:": {
        "glyph": "F:",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/fcap",
        "monad": {
            "name": "Fold",
            "description": "All limited Folds can be thought of as variants of Fold Multiple Forward (F:.). Therefore F:. will be discussed first, and differences in the other Fold variants will be discussed with respect to F:. ."
        },
        "dyad": {
            "name": "Fold",
            "description": "1. Write a while loop without introducing special syntax or control words."
        }
    },
    "F:.": {
        "glyph": "F:.",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/fcap",
        "monad": {
            "name": "Fold",
            "description": "All limited Folds can be thought of as variants of Fold Multiple Forward (F:.). Therefore F:. will be discussed first, and differences in the other Fold variants will be discussed with respect to F:. ."
        },
        "dyad": {
            "name": "Fold",
            "description": "1. Write a while loop without introducing special syntax or control words."
        }
    },
    "F::": {
        "glyph": "F::",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/fcap",
        "monad": {
            "name": "Fold",
            "description": "All limited Folds can be thought of as variants of Fold Multiple Forward (F:.). Therefore F:. will be discussed first, and differences in the other Fold variants will be discussed with respect to F:. ."
        },
        "dyad": {
            "name": "Fold",
            "description": "1. Write a while loop without introducing special syntax or control words."
        }
    },
    "H.": {
        "glyph": "H.",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/hcapdot",
        "monad": {
            "name": "Hypergeometric",
            "description": "x (m H. n) y sums x terms of a generalized hypergeometric series."
        }
    },
    "L:": {
        "glyph": "L:",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/lcapco",
        "monad": {
            "name": "Level At",
            "description": "(u L:0 y) creates a copy of y in which each leaf has been replaced by the result of applying u to the leaf."
        }
    },
    "S:": {
        "glyph": "S:",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/scapco",
        "monad": {
            "name": "Spread",
            "description": "(u S:0 y) applies verb u to each leaf of y, creating an array whose items are the results of the leaves, with framing fill added as needed."
        }
    },
    "t:": {
        "glyph": "t:",
        "type": "adverb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/tco",
        "monad": {
            "name": "Weighted Taylor",
            "description": "The y-th coefficient(s) in the Taylor series that approximates the function (u), multiplied by (!y)."
        }
    },
    "T.": {
        "glyph": "T.",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/tcapdot",
        "monad": {
            "name": "Set Debug Thread",
            "description": "T. y sets the debug thread number to y. The master thread is always thread 0. On entry into debug suspension, the debug thread is set to the number of the thread that caused the suspension."
        },
        "dyad": {
            "name": "Threads/Tasks",
            "description": "x T. y performs a thread- and task-related function depending on the value of x:"
        }
    },
    "Z:": {
        "glyph": "Z:",
        "type": "conjunction",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/zcapco",
        "monad": {
            "name": "Get Fold Status",
            "description": "Rank Infinity -- operates on x and y as a whole -- WHY IS THIS IMPORTANT?"
        },
        "dyad": {
            "name": "Terminate Fold",
            "description": "1. Halt Unlimited Fold (F. or F:) after N iterations of Fold operand u or raise limit error."
        }
    },
    "$:": {
        "glyph": "$:",
        "type": "verb",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/dollarco",
        "monad": {
            "name": "Self-Reference",
            "description": "Stands for the verb currently being executed. If $: occurs directly within:"
        },
        "dyad": {
            "name": "Self-Reference",
            "description": "Rank Infinity -- operates on [x and] y as a whole -- WHY IS THIS IMPORTANT?"
        }
    },
    "[.": {
        "glyph": "[.",
        "type": "other",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/squarelfdot",
        "monad": {
            "name": "Lev",
            "description": ""
        }
    },
    "[:": {
        "glyph": "[:",
        "type": "other",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/squarelfco",
        "monad": {
            "name": "Cap",
            "description": "1. Raises valence error whenever executed as monad or dyad, whatever the argument(s)."
        }
    },
    "].": {
        "glyph": "].",
        "type": "other",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/squarertdot",
        "monad": {
            "name": "Dex",
            "description": ""
        }
    },
    "]:": {
        "glyph": "]:",
        "type": "other",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/squarertco",
        "monad": {
            "name": "Ident",
            "description": ""
        }
    },
    "_": {
        "glyph": "_",
        "type": "noun",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/under",
        "monad": {
            "name": "Negative Sign/Infinity",
            "description": "As the first character of a numeric constant, (_) acts as a negative sign to produce a negative constant."
        }
    },
    "_.": {
        "glyph": "_.",
        "type": "noun",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/underdot",
        "monad": {
            "name": "Indeterminate",
            "description": "Indeterminate (_.) is a numeric atom. It is a placeholder broadly comparable with NaN (not a number). See: WikiPedia:NaN and Essays/Indeterminate."
        }
    },
    "a.": {
        "glyph": "a.",
        "type": "noun",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/adot",
        "monad": {
            "name": "Alphabet",
            "description": "The alphabet of the J language — a built-in list of all bytes"
        }
    },
    "a:": {
        "glyph": "a:",
        "type": "noun",
        "docUrl": "https://code.jsoftware.com/wiki/Vocabulary/aco",
        "monad": {
            "name": "Ace (Boxed Empty)",
            "description": "An atom consisting of the boxed empty list (<0$0)."
        }
    }
};

/**
 * Get hover content for a J primitive
 * @param {string} glyph - The glyph to look up
 * @returns {object|null} - The documentation object or null if not found
 */
export function getJHoverContent(glyph) {
    return jGlyphDocs[glyph] || null;
}
